# Generated by Django 4.2.5 on 2023-10-07 23:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='total_rating',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media/user/'),
        ),
    ]
