# Generated by Django 4.2.5 on 2023-11-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_email_alter_customuser_first_name_and_more'),
        ('mande_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='worker_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mande_app.worker_job'),
        ),
        migrations.AlterField(
            model_name='worker_job',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mande_app.job'),
        ),
        migrations.AlterField(
            model_name='worker_job',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker'),
        ),
    ]
