# Generated by Django 4.2.5 on 2023-11-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_app', '0002_alter_service_customer_alter_service_worker_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker_job',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
