# Generated by Django 4.2.5 on 2023-11-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='as_customer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
