name: Django Test

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main", "develop", "release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      SECRET_KEY: ${{ secrets.DJANGO_KEY }}
    
    steps:
    - name: Verify key
      run: echo "the key is ${{ secrets.DJANGO_KEY }}"
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Coverage report
      run: |
        coverage run manage.py test
        coverage report
    - name: Run Tests
      run: |
        python manage.py test
